(()=>{'use strict';
const KEY='dtail_studio_4_local';
const SERVICES=[{id:'fresh',name:'Fresh Interior',price:19990,desc:'Rendszeres prémium belső tisztítás'},{id:'deep',name:'Deep Interior',price:39990,desc:'Mélytisztítás, extrakció és foltkezelés'}];
const EXTRAS=[{id:'extract',name:'Extra kárpittisztítás / extrakció',price:5000},{id:'pet',name:'Állatszőr eltávolítás',price:9990},{id:'ozone',name:'Ózonos szagtalanítás',price:2000},{id:'trunk',name:'Csomagtér mélytisztítás',price:4990},{id:'spot',name:'Erős / speciális foltkezelés',price:4990}];
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('hu-HU').format(Math.round(Number(n)||0))+' Ft';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=p=>p+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,7).toUpperCase();
const D=x=>new Date(x),fmtDate=x=>new Intl.DateTimeFormat('hu-HU',{dateStyle:'medium'}).format(D(x)),fmtTime=x=>new Intl.DateTimeFormat('hu-HU',{hour:'2-digit',minute:'2-digit'}).format(D(x));
const sameDay=(a,b)=>D(a).toDateString()===D(b).toDateString(),closed=j=>j.status==='closed'||!!j.closedAt;
const DEFAULT_STOCK=[
{id:'ST-APC',name:'ADBL APC',qty:2.5,unit:'liter',min:1,price:5200,category:'Vegyszer'},
{id:'ST-INT',name:'ADBL Interior Cleaner',qty:1.8,unit:'liter',min:.8,price:4500,category:'Vegyszer'},
{id:'ST-SNOW',name:'ADBL Snow Foam',qty:1.2,unit:'liter',min:.5,price:6900,category:'Vegyszer'},
{id:'ST-TIRE',name:'ADBL Tire Dressing',qty:1,unit:'liter',min:.4,price:5900,category:'Vegyszer'},
{id:'ST-TOWEL',name:'Mikroszálas kendő',qty:18,unit:'db',min:8,price:1200,category:'Textil'},
{id:'ST-TEXT',name:'Kárpittisztító vegyszer',qty:1.5,unit:'liter',min:.6,price:7900,category:'Vegyszer'}
];
const state={jobs:[],customers:[],cars:[],stock:[],photos:{},goal:1000000,service:SERVICES[0],extras:[],editJob:null,editCustomer:null,autoDiscount:true,recipes:{},stockMovements:[],recipeTarget:null,cal:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
function defaultRecipes(){return{fresh:[{stockId:'ST-APC',qty:80,unit:'ml'},{stockId:'ST-INT',qty:100,unit:'ml'},{stockId:'ST-TOWEL',qty:.2,unit:'db'}],deep:[{stockId:'ST-APC',qty:150,unit:'ml'},{stockId:'ST-INT',qty:200,unit:'ml'},{stockId:'ST-TEXT',qty:250,unit:'ml'}]}}
function read(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}}
function normalizeStock(a){return(Array.isArray(a)?a:[]).map(x=>({id:x.id||uid('ST'),name:x.name||'Új termék',qty:Number(x.qty)||0,unit:x.unit||'db',min:Number(x.min??x.min_qty)||0,price:Number(x.price??x.unit_price)||0,category:x.category||'Egyéb'}))}
function migrateJobs(a){return(Array.isArray(a)?a:[]).map(j=>{const st=j.startAt||j.start_at||j.date||new Date().toISOString();return{id:j.id||uid('DT'),customerId:j.customerId||j.customer_id||null,carId:j.carId||j.car_id||null,customerName:j.customerName||j.customer_name||'Ismeretlen ügyfél',phone:j.phone||'',car:j.car||j.car_label||'Ismeretlen autó',plate:(j.plate||'').toUpperCase(),year:Number(j.year)||null,km:Number(j.km)||0,serviceId:j.serviceId||j.service_id||'fresh',serviceName:j.serviceName||j.service_name||'Fresh Interior',servicePrice:Number(j.servicePrice??j.service_price??19990),extras:Array.isArray(j.extras)?j.extras:[],discount:Number(j.discount)||0,cost:Number(j.cost)||0,total:Number(j.total)||0,status:j.status||'open',paymentMethod:j.paymentMethod||j.payment_method||'',note:j.note||'',checklist:j.checklist||{before:false,damage:false,after:false},startAt:st,endAt:j.endAt||j.end_at||new Date(D(st).getTime()+180*60000).toISOString(),closedAt:j.closedAt||j.closed_at||null,createdAt:j.createdAt||j.created_at||new Date().toISOString()}})}
function save(){localStorage.setItem(KEY,JSON.stringify({jobs:state.jobs,customers:state.customers,cars:state.cars,stock:state.stock,photos:state.photos,goal:state.goal,recipes:state.recipes,stockMovements:state.stockMovements}))}
function load(){const x=read(KEY,null);if(x){Object.assign(state,x);state.jobs=migrateJobs(state.jobs);state.stock=normalizeStock(state.stock);state.goal=Number(state.goal)||1000000;state.recipes=state.recipes||{};state.stockMovements=Array.isArray(state.stockMovements)?state.stockMovements:[];return}const v3=read('dtail_studio_v3_local',null);if(v3){state.jobs=migrateJobs(v3.jobs);state.customers=v3.customers||[];state.cars=v3.cars||[];state.stock=normalizeStock(v3.stock?.length?v3.stock:DEFAULT_STOCK);state.photos=v3.photos||{};state.goal=Number(v3.goal)||1000000;state.recipes=v3.recipes||defaultRecipes();state.stockMovements=Array.isArray(v3.stockMovements)?v3.stockMovements:[];save();return}state.jobs=migrateJobs(read('dtail_jobs',[]));state.customers=read('dtail_customers',[]);const old=read('dtail_inventory_v2',[]);state.stock=normalizeStock(old.length?old:DEFAULT_STOCK);state.recipes=defaultRecipes();state.stockMovements=[];save()}
function loyaltyByVisits(visits){
 const v=Math.max(0,Number(visits)||0);
 if(v>=15)return{id:'PLATINUM',label:'PLATINUM',discount:15,min:15,next:null,nextLabel:null,cls:'tier-platinum'};
 if(v>=10)return{id:'GOLD',label:'GOLD',discount:10,min:10,next:15,nextLabel:'PLATINUM',cls:'tier-gold'};
 if(v>=6)return{id:'SILVER',label:'SILVER',discount:7,min:6,next:10,nextLabel:'GOLD',cls:'tier-silver'};
 if(v>=3)return{id:'BRONZE',label:'BRONZE',discount:5,min:3,next:6,nextLabel:'SILVER',cls:'tier-bronze'};
 return{id:'NEW',label:'NEW',discount:0,min:0,next:3,nextLabel:'BRONZE',cls:'tier-new'};
}
function customerByName(name){
 const q=String(name||'').trim().toLowerCase();
 return q?state.customers.find(c=>String(c.name||'').trim().toLowerCase()===q)||null:null;
}
function customerLoyalty(name){
 const c=customerByName(name);
 if(!c)return{...loyaltyByVisits(0),visits:0};
 const visits=state.jobs.filter(j=>closed(j)&&(j.customerId===c.id||String(j.customerName||'').trim().toLowerCase()===String(c.name||'').trim().toLowerCase())).length;
 return{...loyaltyByVisits(visits),visits,name:c.name};
}
function updateCustomerReward(){
 const box=$('customerReward');
 if(!box)return;
 const name=$('fCustomer').value.trim();
 if(!name){box.style.display='none';return;}
 const t=customerLoyalty(name);
 box.style.display='block';
 const next=t.next?'Még '+(t.next-t.visits)+' alkalom a '+t.nextLabel+' szintig.':'Legmagasabb szint.';
 const progress=t.next?Math.max(0,Math.min(100,((t.visits-t.min)/(t.next-t.min))*100)):100;
 box.innerHTML='<div class="reward-line"><div><div class="reward-title">★ '+t.label+' · '+t.visits+' visszatérés</div><div style="margin-top:3px">'+next+'</div></div><div class="reward-discount">'+(t.discount?t.discount+'% kedvezmény':'Nincs kedvezmény')+'</div></div><div class="reward-progress"><i style="width:'+progress+'%"></i></div>';
}
function applyLoyaltyDiscount(){
 if(state.editJob||!state.autoDiscount)return;
 const t=customerLoyalty($('fCustomer').value);
 $('fDiscount').value=t.discount?Math.round((state.service.price+state.extras.reduce((s,x)=>s+x.price,0))*t.discount/100):0;
 updateCustomerReward();
 renderCart();
}

function greeting(){const h=new Date().getHours();$('greeting').textContent=h<11?'Jó reggelt, Dominik! ☀️':h<18?'Szia Dominik! 👋':h<23?'Szép estét, Dominik! 🌙':'Jó éjszakát, Dominik! 🌙';$('todayText').textContent=new Intl.DateTimeFormat('hu-HU',{dateStyle:'full'}).format(new Date())}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('view-'+v)?.classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.body.classList.remove('drawer');renderAll()}
function openNew(at){state.editJob=null;state.autoDiscount=true;state.service=SERVICES[0];state.extras=[];['fCustomer','fPhone','fCar','fPlate','fYear','fKm','fNote'].forEach(id=>$(id).value='');$('fCost').value=0;$('fDiscount').value=0;$('fDuration').value=180;const d=at?D(at):new Date();$('fDate').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);renderServices();renderCart();$('jobModal').classList.add('show')}
function openEdit(id){const j=state.jobs.find(x=>x.id===id);if(!j)return;state.editJob=id;state.autoDiscount=false;state.service=SERVICES.find(s=>s.id===j.serviceId)||SERVICES[0];state.extras=(j.extras||[]).slice();$('fCustomer').value=j.customerName||'';$('fPhone').value=j.phone||'';$('fCar').value=j.car||'';$('fPlate').value=j.plate||'';$('fYear').value=j.year||'';$('fKm').value=j.km||'';const d=D(j.startAt);$('fDate').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$('fDuration').value=Math.max(15,Math.round((D(j.endAt)-d)/60000));$('fCost').value=j.cost||0;$('fDiscount').value=j.discount||0;$('fNote').value=j.note||'';renderServices();renderCart();$('jobModalTitle').textContent='Szerkesztés · '+j.id;$('jobModal').classList.add('show')}
function renderServices(){$('serviceGrid').innerHTML=SERVICES.map(s=>'<div class="service '+(state.service.id===s.id?'sel':'')+'" data-service="'+s.id+'"><b>'+esc(s.name)+'</b><strong>'+money(s.price)+'</strong><p>'+esc(s.desc)+'</p></div>').join('');$('extraGrid').innerHTML=EXTRAS.map(x=>'<div class="service '+(state.extras.some(e=>e.id===x.id)?'sel':'')+'" data-extra="'+x.id+'"><b>'+esc(x.name)+'</b><strong>+'+money(x.price)+'</strong></div>').join('');document.querySelectorAll('[data-service]').forEach(e=>e.onclick=()=>{state.service=SERVICES.find(s=>s.id===e.dataset.service)||SERVICES[0];if(state.autoDiscount)applyLoyaltyDiscount();else{renderServices();renderCart()}});document.querySelectorAll('[data-extra]').forEach(e=>e.onclick=()=>{const x=EXTRAS.find(s=>s.id===e.dataset.extra);state.extras=state.extras.some(s=>s.id===x.id)?state.extras.filter(s=>s.id!==x.id):state.extras.concat(x);renderServices();renderCart()})}
function total(){return Math.max(0,state.service.price+state.extras.reduce((s,x)=>s+x.price,0)-(Number($('fDiscount').value)||0))}
function renderCart(){const st=new Date($('fDate').value),en=new Date(st.getTime()+Math.max(15,Number($('fDuration').value)||180)*60000),conf=state.jobs.filter(j=>j.id!==state.editJob&&!closed(j)&&st<D(j.endAt)&&en>D(j.startAt));$('cartLines').innerHTML='<div class="cart-line"><span>'+esc(state.service.name)+'</span><b>'+money(state.service.price)+'</b></div>'+state.extras.map(x=>'<div class="cart-line"><span>'+esc(x.name)+'</span><b>+'+money(x.price)+'</b></div>').join('')+((Number($('fDiscount').value)||0)?'<div class="cart-line"><span>Kedvezmény</span><b>−'+money(Number($('fDiscount').value))+'</b></div>':'');$('cartTotal').textContent=money(total());$('conflictNotice').style.display=conf.length?'block':'none';$('conflictNotice').innerHTML=conf.length?'<b>Időpontütközés</b><br>'+conf.map(j=>fmtTime(j.startAt)+'–'+fmtTime(j.endAt)+' · '+esc(j.customerName)).join('<br>'):'';const m=materialEstimateForJob({serviceId:state.service.id,extras:state.extras});$('fCost').value=Math.round(m.total);$('materialBreakdown').innerHTML=m.lines.length?'<b>Anyagbecslés</b>'+m.lines.map(x=>'<div style="display:flex;justify-content:space-between;margin-top:4px"><span>'+esc(x.name)+' · '+x.qty+' '+esc(x.unit)+'</span><b>'+money(x.cost)+'</b></div>').join('')+'<div style="margin-top:7px;padding-top:7px;border-top:1px solid var(--line);display:flex;justify-content:space-between"><span>Összes anyagköltség</span><b>'+money(m.total)+'</b></div>'+(m.shortages.length?'<div style="margin-top:6px;color:var(--r)">⚠ Nincs elég készlet: '+m.shortages.map(x=>esc(x.name)).join(', ')+'</div>':''):'Nincs anyagrecept beállítva.'}function connect(j){let c=state.customers.find(x=>x.id===j.customerId)||state.customers.find(x=>String(x.name).toLowerCase()===String(j.customerName).toLowerCase());if(!c){c={id:uid('CU'),name:j.customerName,phone:j.phone||'',email:'',note:''};state.customers.push(c)}else c.phone=j.phone||c.phone;j.customerId=c.id;let car=state.cars.find(x=>x.id===j.carId)||state.cars.find(x=>x.customerId===c.id&&x.makeModel===j.car&&x.plate===j.plate);if(!car){car={id:uid('CAR'),customerId:c.id,makeModel:j.car,plate:j.plate||'',year:j.year||null,km:j.km||0};state.cars.push(car)}j.carId=car.id}
function saveJob(){const st=new Date($('fDate').value),dur=Math.max(15,Number($('fDuration').value)||180),en=new Date(st.getTime()+dur*60000),conf=state.jobs.filter(j=>j.id!==state.editJob&&!closed(j)&&st<D(j.endAt)&&en>D(j.startAt));if(conf.length&&!confirm('Az időpont ütközik. Mentsem így is?'))return;const old=state.jobs.find(j=>j.id===state.editJob),j={id:state.editJob||uid('DT'),customerName:$('fCustomer').value.trim()||'Ismeretlen ügyfél',phone:$('fPhone').value.trim(),car:$('fCar').value.trim()||'Ismeretlen autó',plate:$('fPlate').value.trim().toUpperCase(),year:Number($('fYear').value)||null,km:Number($('fKm').value)||0,startAt:st.toISOString(),endAt:en.toISOString(),serviceId:state.service.id,serviceName:state.service.name,servicePrice:state.service.price,extras:state.extras.slice(),discount:Number($('fDiscount').value)||0,cost:Math.round(materialEstimateForJob({serviceId:state.service.id,extras:state.extras}).total),total:total(),status:old?.status||'open',paymentMethod:old?.paymentMethod||'',note:$('fNote').value.trim(),checklist:old?.checklist||{before:false,damage:false,after:false},closedAt:old?.closedAt||null,createdAt:old?.createdAt||new Date().toISOString()};connect(j);const i=state.jobs.findIndex(x=>x.id===j.id);if(i>=0)state.jobs[i]=j;else state.jobs.unshift(j);save();$('jobModal').classList.remove('show');renderAll();openDetail(j.id);toast('Munkalap mentve')}
function openDetail(id){const j=state.jobs.find(x=>x.id===id);if(!j)return;const ph=state.photos[id]||[];$('detailTitle').textContent=j.id+' · '+j.customerName;$('detailBody').innerHTML='<div class="grid two"><div><div class="info"><b>'+esc(j.customerName)+'</b><br>'+esc(j.phone||'Nincs telefon')+'</div><div class="info" style="margin-top:8px"><b>'+esc(j.car)+'</b><br>'+esc(j.plate||'Nincs rendszám')+' · '+(j.year||'—')+'</div><div class="info" style="margin-top:8px"><b>'+esc(j.serviceName)+'</b><br>'+((j.extras||[]).map(x=>esc(x.name)).join(' · ')||'Nincs extra')+'</div><div class="info" style="margin-top:8px"><b>'+fmtDate(j.startAt)+'</b><br>'+fmtTime(j.startAt)+'–'+fmtTime(j.endAt)+'</div></div><div><div class="info"><b>'+money(j.total)+'</b><br>'+(j.paymentMethod?esc(j.paymentMethod):'Fizetés nincs rögzítve')+' · '+(closed(j)?'LEZÁRVA':'NYITOTT')+'</div><div class="actions"><button class="secondary" id="dEdit">✎ Szerkesztés</button><button class="secondary" id="dPay">💳 Fizetés</button><button class="secondary" id="dClose">'+(closed(j)?'↩ Újranyitás':'✓ Lezárás')+'</button><button class="secondary" id="dPrint">▣ Dizájnos PDF</button></div></div></div><div class="head" style="margin-top:18px"><h3>Fotódokumentáció</h3><span>BEFORE · PROCESS · AFTER</span></div><div class="grid two"><select id="photoLabel" class="select"><option>BEFORE</option><option>PROCESS</option><option>AFTER</option><option>Sérülés</option></select><input id="photoInput" class="input" type="file" accept="image/*" capture="environment" multiple></div><div class="photo-grid" style="margin-top:8px">'+(ph.length?ph.map(p=>'<div class="photo"><img src="'+p.data+'"><small>'+esc(p.label)+'</small></div>').join(''):'<div class="info">Még nincs fotó.</div>')+'</div>';$('detailModal').classList.add('show');$('dEdit').onclick=()=>{$('detailModal').classList.remove('show');openEdit(id)};$('dPay').onclick=()=>pay(id);$('dClose').onclick=()=>toggleClose(id);$('dPrint').onclick=()=>printJob(id);$('photoInput').onchange=e=>addPhotos(id,e.target.files)}
function pay(id){const j=state.jobs.find(x=>x.id===id),m=prompt('Fizetési mód: Készpénz / Átutalás / Bankkártya',j.paymentMethod||'Bankkártya');if(!m)return;j.paymentMethod=m.trim();save();renderAll();openDetail(id);toast('Fizetés mentve')}
function logMovement(stockId,qty,kind,reason,ref){state.stockMovements.unshift({id:uid('MOV'),stockId,qty,kind,reason,ref:ref||'',at:new Date().toISOString()});state.stockMovements=state.stockMovements.slice(0,100)}
function applyInventoryToJob(j){if(j.inventoryAppliedAt)return true;const m=materialEstimateForJob(j);if(m.missing.length){toast('A receptben ismeretlen termék van.');return false}if(m.shortages.length){toast('Nincs elegendő készlet: '+m.shortages.map(x=>x.name).join(', '));return false}const applied=[];m.lines.forEach(x=>{const s=x.stock;s.qty=Number(s.qty)-x.stockQty;applied.push({stockId:s.id,qty:x.stockQty,cost:x.cost,name:s.name,unit:s.unit});logMovement(s.id,-x.stockQty,'consumption','Felhasználás · '+j.id,j.id)});j.inventoryConsumption=applied;j.inventoryAppliedAt=new Date().toISOString();j.cost=Math.round(m.total);return true}
function reverseInventoryFromJob(j){if(!j.inventoryAppliedAt||!Array.isArray(j.inventoryConsumption))return true;j.inventoryConsumption.forEach(x=>{const s=state.stock.find(z=>z.id===x.stockId);if(s){s.qty=Number(s.qty)+Number(x.qty);logMovement(s.id,Number(x.qty),'reversal','Visszaírás · '+j.id,j.id)}});j.inventoryConsumption=[];j.inventoryAppliedAt=null;return true}
function toggleClose(id){const j=state.jobs.find(x=>x.id===id);if(closed(j)){reverseInventoryFromJob(j);j.status='open';j.closedAt=null;save();renderAll();openDetail(id);toast('Munkalap újranyitva · készlet visszaírva');return}if(!j.paymentMethod){toast('Előbb rögzíts fizetési módot');return}if(!applyInventoryToJob(j))return;j.status='closed';j.closedAt=new Date().toISOString();save();renderAll();openDetail(id);toast('Munkalap lezárva · készlet levonva')}
function addPhotos(id,files){const label=$('photoLabel').value;state.photos[id]||(state.photos[id]=[]);Array.from(files||[]).forEach(file=>{const r=new FileReader();r.onload=()=>{state.photos[id].push({id:uid('PH'),label,data:r.result});save();openDetail(id)};r.readAsDataURL(file)});toast('Fotó hozzáadva')}
function renderJobs(){const q=$('jobSearch').value.toLowerCase(),f=$('jobFilter').value,a=state.jobs.filter(j=>(f==='all'||(f==='open'&&!closed(j))||(f==='closed'&&closed(j)))&&JSON.stringify(j).toLowerCase().includes(q)).sort((a,b)=>D(b.startAt)-D(a.startAt));$('jobsTable').innerHTML=a.length?a.map(j=>'<tr><td><b>'+esc(j.id)+'</b><br><span class="muted">'+fmtDate(j.startAt)+'</span></td><td><b>'+esc(j.customerName)+'</b><br><span class="muted">'+esc(j.car)+(j.plate?' · '+esc(j.plate):'')+'</span></td><td>'+esc(j.serviceName)+'</td><td>'+fmtTime(j.startAt)+'–'+fmtTime(j.endAt)+'</td><td>'+money(j.total)+'</td><td><span class="badge '+(closed(j)?'ok':'warn')+'">'+(closed(j)?'Lezárt':'Nyitott')+'</span></td><td><button class="secondary" data-open-job="'+esc(j.id)+'">Megnyitás</button></td></tr>').join(''):'<tr><td colspan="7" class="muted">Nincs találat.</td></tr>';document.querySelectorAll('[data-open-job]').forEach(b=>b.onclick=()=>openDetail(b.dataset.openJob))}
function renderCustomers(){
 const q=$('customerSearch').value.toLowerCase();
 const map=new Map(state.customers.map(c=>[c.id,{...c,jobs:[],cars:[]}]));state.cars.forEach(c=>map.get(c.customerId)?.cars.push(c));
 state.jobs.forEach(j=>{const c=map.get(j.customerId)||[...map.values()].find(x=>String(x.name).toLowerCase()===String(j.customerName).toLowerCase());if(c)c.jobs.push(j)});
 const a=[...map.values()].filter(c=>JSON.stringify(c).toLowerCase().includes(q));
 $('customerTable').innerHTML=a.length?a.map(c=>{const js=c.jobs.filter(closed),sp=js.reduce((s,x)=>s+x.total,0),t=loyaltyByVisits(js.length);return'<tr><td><b>'+esc(c.name)+'</b><br><span class="muted">'+esc(c.phone||'')+'</span></td><td>'+((c.cars||[]).map(x=>esc(x.makeModel)+(x.plate?' · '+esc(x.plate):'')).join('<br>')||'—')+'</td><td>'+js.length+'</td><td>'+money(sp)+'</td><td><span class="badge '+t.cls+'">'+t.label+'</span><br><span class="muted" style="font-size:8px">'+js.length+' alkalom</span></td><td><b style="color:'+(t.discount?'var(--a)':'var(--muted)')+'">'+(t.discount?t.discount+'%':'—')+'</b></td><td><button class="secondary" data-customer="'+esc(c.id)+'">Megnyitás</button></td></tr>'}).join(''):'<tr><td colspan="7" class="muted">Nincs ügyfél.</td></tr>';
 document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>openCustomer(b.dataset.customer));
}
function openCustomer(id){const c=id?state.customers.find(x=>x.id===id):null;state.editCustomer=id||null;$('customerModalTitle').textContent=c?'Ügyfél szerkesztése':'Új ügyfél';$('cuName').value=c?.name||'';$('cuPhone').value=c?.phone||'';$('cuEmail').value=c?.email||'';$('cuNote').value=c?.note||'';$('customerModal').classList.add('show')}
function saveCustomer(){const c={id:state.editCustomer||uid('CU'),name:$('cuName').value.trim()||'Ismeretlen',phone:$('cuPhone').value.trim(),email:$('cuEmail').value.trim(),note:$('cuNote').value.trim()};const i=state.customers.findIndex(x=>x.id===c.id);if(i>=0)state.customers[i]=c;else state.customers.push(c);save();$('customerModal').classList.remove('show');renderAll();toast('Ügyfél mentve')}
function renderCalendar(){const m=state.cal,y=m.getFullYear(),mo=m.getMonth(),first=new Date(y,mo,1),start=(first.getDay()+6)%7,days=new Date(y,mo+1,0).getDate(),prev=new Date(y,mo,0).getDate(),cells=Math.ceil((start+days)/7)*7,heads=['H','K','Sze','Cs','P','Szo','V'];let h=heads.map(x=>'<div class="dow">'+x+'</div>').join('');for(let i=0;i<cells;i++){const dn=i-start+1;let d;if(dn<1)d=new Date(y,mo-1,prev+dn);else if(dn>days)d=new Date(y,mo+1,dn-days);else d=new Date(y,mo,dn);const ev=state.jobs.filter(j=>sameDay(j.startAt,d)).sort((a,b)=>D(a.startAt)-D(b.startAt));h+='<div class="day '+(sameDay(d,new Date())?'today':'')+'"><div class="day-num"><button class="secondary" style="padding:2px 6px;font-size:8px;float:right" data-day="'+d.toISOString()+'">+</button>'+d.getDate()+'</div>'+ev.slice(0,4).map(j=>'<button class="day-event" data-cal="'+esc(j.id)+'">'+fmtTime(j.startAt)+' · '+esc(j.customerName)+'</button>').join('')+'</div>'}$('calendarGrid').innerHTML=h;$('calTitle').textContent=new Intl.DateTimeFormat('hu-HU',{month:'long',year:'numeric'}).format(m).replace(/^./,c=>c.toUpperCase());$('calendarDate').textContent=new Intl.DateTimeFormat('hu-HU',{dateStyle:'full'}).format(new Date());document.querySelectorAll('[data-cal]').forEach(b=>b.onclick=()=>openDetail(b.dataset.cal));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>openNew(b.dataset.day));const t=state.jobs.filter(j=>sameDay(j.startAt,new Date())).sort((a,b)=>D(a.startAt)-D(b.startAt));$('calendarToday').innerHTML=t.length?t.map(j=>'<div class="row"><div><b>'+fmtTime(j.startAt)+' · '+esc(j.customerName)+'</b><p>'+esc(j.car)+' · '+esc(j.serviceName)+'</p></div><span class="badge '+(closed(j)?'ok':'warn')+'">'+(closed(j)?'Lezárt':'Nyitott')+'</span></div>').join(''):'<div class="muted" style="font-size:9px">Nincs mai időpont.</div>';const n=state.jobs.filter(j=>!closed(j)&&D(j.startAt)>new Date()).sort((a,b)=>D(a.startAt)-D(b.startAt)).slice(0,8);$('upcoming').innerHTML=n.length?n.map(j=>'<div class="row"><div><b>'+fmtDate(j.startAt)+' · '+fmtTime(j.startAt)+'</b><p>'+esc(j.customerName)+' · '+esc(j.car)+'</p></div><button class="secondary" data-up="'+esc(j.id)+'">Megnyitás</button></div>').join(''):'<div class="muted" style="font-size:9px">Nincs következő időpont.</div>';document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>openDetail(b.dataset.up))}
function inventoryRow(x){const s=stockState(x),uc=stockUnitCost(x);return'<tr data-stock="'+esc(x.id)+'"><td><input class="input stock-name" value="'+esc(x.name)+'"></td><td><input class="input stock-category" value="'+esc(x.category||'Egyéb')+'"></td><td><input class="input stock-qty" type="number" step="0.01" value="'+(Number(x.qty)||0)+'"><div class="muted" style="font-size:8px;margin-top:3px">'+esc(x.unit)+'</div></td><td><input class="input stock-min" type="number" step="0.01" value="'+(Number(x.min)||0)+'"></td><td><span class="muted">'+(Number(x.packQty)||0)+' '+esc(x.packUnit||x.unit)+' · '+money(x.packPrice)+'</span><div style="font-size:8px;margin-top:4px"><b>'+money(uc)+' / '+esc(x.unit)+'</b></div></td><td>'+money(uc)+'</td><td>'+money(stockValue(x))+'</td><td><span class="badge '+(s==='critical'?'danger':s==='low'?'warn':'ok')+'">'+stockLabel(x)+'</span></td><td><button class="secondary" data-delete-stock="'+esc(x.id)+'">Törlés</button></td></tr>'}
function renderInventory(){const rank={critical:0,low:1,ok:2},search=($('inventorySearch')?.value||'').toLowerCase(),status=$('inventoryStatus')?.value||'all',cat=$('inventoryCategory')?.value||'all',all=state.stock.slice(),filtered=all.filter(x=>(status==='all'||stockState(x)===status)&&(cat==='all'||(x.category||'Egyéb')===cat)&&String(x.name+' '+(x.category||'')).toLowerCase().includes(search)).sort((x,y)=>rank[stockState(x)]-rank[stockState(y)]||String(x.name).localeCompare(String(y.name),'hu')),critical=all.filter(x=>stockState(x)==='critical').length,low=all.filter(x=>stockState(x)==='low').length,cats=[...new Set(all.map(x=>x.category||'Egyéb'))].sort((x,y)=>x.localeCompare(y,'hu'));$('inventoryCategory').innerHTML='<option value="all">Minden kategória</option>'+cats.map(x=>'<option value="'+esc(x)+'" '+(x===cat?'selected':'')+'>'+esc(x)+'</option>').join('');$('inventoryVisualMeta').textContent=filtered.length+' / '+all.length+' tétel · '+critical+' piros · '+low+' sárga';$('dashStockMeta').textContent=all.length+' tétel';$('dashStock').innerHTML=all.length?all.slice().sort((x,y)=>rank[stockState(x)]-rank[stockState(y)]).map(stockCard).join(''):'<div class="muted">Nincs készlet.</div>';$('inventoryVisual').innerHTML=filtered.length?filtered.map(stockCard).join(''):'<div class="recipe-empty">A szűrésnek megfelelő készlet nincs.</div>';$('invCount').textContent=all.length;$('invCritical').textContent=critical;$('invLow').textContent=low;$('invValue').textContent=money(all.reduce((s,x)=>s+stockValue(x),0));$('inventoryEditor').innerHTML=filtered.length?filtered.map(inventoryRow).join(''):'<tr><td colspan="9" class="muted">Nincs találat.</td></tr>';renderRecipes();renderMovements()}
function stockCard(x){const s=stockState(x),target=Math.max((Number(x.min)||0)*3,1),pct=x.unit==='%'?Math.min(100,Math.max(0,Number(x.qty)||0)):Math.min(100,Math.max(0,(Number(x.qty)||0)/target*100));return'<div class="card stock '+s+'"><div class="stock-top"><b>'+esc(x.name)+'</b><span>'+(Number(x.qty)||0)+' '+esc(x.unit)+'</span></div><div class="bar"><i style="width:'+pct+'%"></i></div><div class="stock-top"><span class="badge '+(s==='critical'?'danger':s==='low'?'warn':'ok')+'">'+stockLabel(x)+'</span><span>'+money(stockValue(x))+'</span></div></div>'}
function renderRecipes(){const targets=SERVICES.map(s=>({key:s.id,name:s.name,kind:'Szolgáltatás'})).concat(EXTRAS.map(e=>({key:recipeKeyForExtra(e.id),name:e.name,kind:'Extra'})));$('recipeCards').innerHTML=targets.map(t=>{const lines=recipeForKey(t.key),cost=lines.reduce((sum,l)=>{const s=state.stock.find(x=>x.id===l.stockId);return sum+(s?Number(l.qty||0)*unitFactor(l.unit)*stockUnitCost(s):0)},0);return'<div class="card recipe-card"><div class="recipe-top"><div><h4>'+esc(t.name)+'</h4><p>'+esc(t.kind)+' · '+lines.length+' anyag</p></div><div class="recipe-total">'+money(cost)+'</div></div>'+(lines.length?lines.map(l=>{const s=state.stock.find(x=>x.id===l.stockId),cost=s?Number(l.qty||0)*unitFactor(l.unit)*stockUnitCost(s):0;return'<div class="recipe-line"><div><b>'+esc(s?.name||'Ismeretlen termék')+'</b><span class="muted"> · '+l.qty+' '+esc(l.unit)+'</span></div><b>'+money(cost)+'</b></div>'}).join(''):'<div class="recipe-empty" style="margin-top:12px">Nincs recept. Kattints a szerkesztéshez.</div>')+'<div class="actions" style="justify-content:space-between"><span class="muted" style="font-size:8px">Záráskor automatikus fogyás</span><button class="secondary" data-edit-recipe="'+esc(t.key)+'">✎ Szerkesztés</button></div></div>'}).join('');document.querySelectorAll('[data-edit-recipe]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.editRecipe))}
function renderMovements(){const a=(state.stockMovements||[]).slice(0,20);$('stockMovements').innerHTML=a.length?a.map(m=>{const s=state.stock.find(x=>x.id===m.stockId),q=Number(m.qty)||0;return'<div class="movement"><div><div class="movement-kind">'+esc(m.kind==='consumption'?'FELHASZNÁLÁS':m.kind==='purchase'?'BESZERZÉS':'VISSZAÍRÁS')+'</div><p>'+fmtDate(m.at)+' · '+fmtTime(m.at)+'</p></div><div><b>'+esc(s?.name||m.stockId)+'</b><p>'+esc(m.reason||'')+'</p></div><div class="qty '+(q>0?'qty-plus':q<0?'qty-minus':'qty-adjust')+'">'+(q>0?'+':'')+q+' '+esc(s?.unit||'db')+'</div></div>'}).join(''):'<div class="recipe-empty">Még nincs készletmozgás.</div>'}
function openRecipe(key){state.recipeTarget=key;const meta=SERVICES.map(s=>({key:s.id,name:s.name})).concat(EXTRAS.map(e=>({key:recipeKeyForExtra(e.id),name:e.name}))).find(x=>x.key===key);$('recipeModalTitle').textContent='Recept · '+(meta?.name||'');$('recipeModalSub').textContent='Felhasználásból számoljuk az anyagköltséget és záráskor a készletfogyást.';$('recipeProduct').innerHTML=state.stock.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>').join('');$('recipeUnit').innerHTML=['db','liter','ml','kg','g'].map(u=>'<option>'+u+'</option>').join('');$('recipeQty').value='';renderRecipeModalLines();$('recipeModal').classList.add('show')}
function renderRecipeModalLines(){const lines=recipeForKey(state.recipeTarget);$('recipeLines').innerHTML=lines.length?lines.map((l,i)=>{const s=state.stock.find(x=>x.id===l.stockId),cost=s?Number(l.qty)*unitFactor(l.unit)*stockUnitCost(s):0;return'<div class="row"><div><b>'+esc(s?.name||'Ismeretlen termék')+'</b><p>'+l.qty+' '+esc(l.unit)+' · '+money(cost)+'</p></div><button class="secondary" data-remove-recipe="'+i+'">Törlés</button></div>'}).join(''):'<div class="recipe-empty">Még nincs anyag hozzáadva.</div>';const total=lines.reduce((sum,l)=>{const s=state.stock.find(x=>x.id===l.stockId);return sum+(s?Number(l.qty)*unitFactor(l.unit)*stockUnitCost(s):0)},0);$('recipeCost').textContent=money(total)+' / alkalom';document.querySelectorAll('[data-remove-recipe]').forEach(b=>b.onclick=()=>{state.recipes[state.recipeTarget].splice(Number(b.dataset.removeRecipe),1);renderRecipeModalLines()})}
function addRecipeLine(){const id=$('recipeProduct').value,qty=Number($('recipeQty').value)||0,unit=$('recipeUnit').value;if(!id||qty<=0){toast('Adj meg terméket és felhasználási mennyiséget');return}state.recipes[state.recipeTarget]||(state.recipes[state.recipeTarget]=[]);state.recipes[state.recipeTarget].push({stockId:id,qty,unit});$('recipeQty').value='';renderRecipeModalLines()}
function saveRecipe(){save();$('recipeModal').classList.remove('show');renderAll();toast('Anyagrecept mentve')}

function saveInventory(){document.querySelectorAll('#inventoryEditor tr[data-stock]').forEach(tr=>{const old=state.stock.find(s=>s.id===tr.dataset.stock);if(!old)return;const x={...old,name:tr.querySelector('.stock-name').value.trim()||old.name,category:tr.querySelector('.stock-category').value.trim()||old.category,qty:Number(tr.querySelector('.stock-qty').value)||0,min:Number(tr.querySelector('.stock-min').value)||0};const diff=x.qty-Number(old.qty||0);if(Math.abs(diff)>1e-9)logMovement(x.id,diff,'adjustment','Kézi készletkorrekció');Object.assign(old,x)});save();renderAll();toast('Készlet mentve')}
function addStock(){$('stockName').value='';$('stockCategory').value='';$('stockQty').value='0';$('stockUnit').value='db';$('stockMin').value='1';$('stockPackQty').value='1';$('stockPackUnit').value='db';$('stockPackPrice').value='0';$('stockUnitCostPreview').textContent='Egységköltség: —';$('stockModalTitle').textContent='Új készlettétel';$('stockModal').classList.add('show')}
function previewNewStockCost(){const x={packQty:Number($('stockPackQty').value)||0,packUnit:$('stockPackUnit').value,packPrice:Number($('stockPackPrice').value)||0,unit:$('stockUnit').value};const u=x.packQty?stockUnitCost(x):0;$('stockUnitCostPreview').textContent=u?('Egységköltség: '+money(u)+' / '+x.unit):'Egységköltség: —'}
function saveStock(){const x={id:uid('ST'),name:$('stockName').value.trim()||'Új termék',category:$('stockCategory').value.trim()||'Egyéb',qty:Number($('stockQty').value)||0,unit:$('stockUnit').value,min:Number($('stockMin').value)||0,packQty:Number($('stockPackQty').value)||1,packUnit:$('stockPackUnit').value,packPrice:Number($('stockPackPrice').value)||0};x.price=stockUnitCost(x);state.stock.push(x);if(x.qty)logMovement(x.id,x.qty,'purchase','Nyitókészlet');save();$('stockModal').classList.remove('show');renderAll();toast('Készlettétel hozzáadva')}
function deleteStock(id){const used=Object.values(state.recipes||{}).some(lines=>Array.isArray(lines)&&lines.some(l=>l.stockId===id))||(state.jobs||[]).some(j=>(j.inventoryConsumption||[]).some(x=>x.stockId===id));if(used){toast('A terméket recept vagy munkatörténet használja. Előbb távolítsd el a receptekből.');return}if(!confirm('Biztosan törlöd ezt a készlettételt?'))return;state.stock=state.stock.filter(x=>x.id!==id);save();renderAll();toast('Készlettétel törölve')}
function renderAnalytics(){const n=new Date(),a=state.jobs.filter(j=>closed(j)&&D(j.startAt).getFullYear()===n.getFullYear()&&D(j.startAt).getMonth()===n.getMonth()),rev=a.reduce((s,j)=>s+j.total,0),cost=a.reduce((s,j)=>s+j.cost,0),svc={},paym={};a.forEach(j=>{svc[j.serviceName]=(svc[j.serviceName]||0)+j.total;paym[j.paymentMethod||'Nincs rögzítve']=(paym[j.paymentMethod||'Nincs rögzítve']||0)+j.total});$('aRevenue').textContent=money(rev);$('aCost').textContent=money(cost);$('aMargin').textContent=money(rev-cost);$('aAvg').textContent=money(a.length?rev/a.length:0);$('serviceMix').innerHTML=Object.entries(svc).map(x=>'<div class="row"><div><b>'+esc(x[0])+'</b><p>'+a.filter(j=>j.serviceName===x[0]).length+' munka</p></div><span class="money">'+money(x[1])+'</span></div>').join('')||'<div class="muted">Nincs adat.</div>';$('paymentMix').innerHTML=Object.entries(paym).map(x=>'<div class="row"><b>'+esc(x[0])+'</b><span class="money">'+money(x[1])+'</span></div>').join('')||'<div class="muted">Nincs adat.</div>';$('financeTable').innerHTML=a.map(j=>'<tr><td>'+fmtDate(j.startAt)+'</td><td>'+esc(j.customerName)+'</td><td>'+esc(j.serviceName)+'</td><td>'+money(j.total)+'</td><td>'+money(j.cost)+'</td><td>'+money(j.total-j.cost)+'</td></tr>').join('')||'<tr><td colspan="6" class="muted">Nincs lezárt munka.</td></tr>'}
function renderDashboard(){const n=new Date(),t=state.jobs.filter(j=>sameDay(j.startAt,n)).sort((a,b)=>D(a.startAt)-D(b.startAt)),m=state.jobs.filter(j=>closed(j)&&D(j.startAt).getFullYear()===n.getFullYear()&&D(j.startAt).getMonth()===n.getMonth()),rev=m.reduce((s,j)=>s+j.total,0),today=t.filter(closed),open=state.jobs.filter(j=>!closed(j));$('sToday').textContent=money(today.reduce((s,j)=>s+j.total,0));$('sTodayJobs').textContent=today.length+' lezárt munka';$('sMonth').textContent=money(rev);$('sMonthJobs').textContent=m.length+' lezárt munka';$('sOpen').textContent=open.length;$('sAvg').textContent=money(m.length?rev/m.length:0);$('todayPlanLabel').textContent=t.length+' időpont';$('todayJobs').innerHTML=t.length?t.map(j=>'<div class="row"><div><b>'+fmtTime(j.startAt)+'–'+fmtTime(j.endAt)+' · '+esc(j.customerName)+'</b><p>'+esc(j.car)+' · '+esc(j.serviceName)+'</p></div><div><span class="badge '+(closed(j)?'ok':'warn')+'">'+(closed(j)?'Lezárt':'Nyitott')+'</span><div class="money">'+money(j.total)+'</div></div></div>').join(''):'<div class="muted" style="font-size:9px">Ma nincs beírt időpont.</div>';const pct=Math.min(100,state.goal?rev/state.goal*100:0);$('goalLabel').textContent=money(rev)+' / '+money(state.goal);$('goalBar').style.width=pct+'%';$('goalText').textContent=pct>=100?'A havi cél teljesítve.':pct.toFixed(0)+'% · '+money(state.goal-rev)+' van hátra.'}
function renderSettings(){$('goalInput').value=state.goal;$('cloudStateLabel').textContent='LOCAL';$('cloudSettings').innerHTML='<b>Stabil helyi mód.</b><br>Vercel API és Service Worker nincs a rendszerben. A felhőszinkron külön rétegként kerül rá, miután a helyi működést leteszteltük.'}
function printJob(id){const j=state.jobs.find(x=>x.id===id),ph=state.photos[id]||[];if(!j)return;const sub=j.servicePrice+(j.extras||[]).reduce((s,x)=>s+Number(x.price||0),0);$('printSheet').innerHTML='<div class="print-page"><div class="print-header"><div class="print-brand"><div><img class="print-logo" src="./assets/dtail-logo.png" alt="D-Tail Studio"><div class="print-sub">Premium detailing · A részletek számítanak.</div></div></div><div class="print-id"><b>'+esc(j.id)+'</b>'+fmtDate(j.startAt)+'<br>'+fmtTime(j.startAt)+'–'+fmtTime(j.endAt)+'</div></div><div class="print-grid"><div class="print-card"><h4>Ügyfél</h4><p><b>'+esc(j.customerName)+'</b><br>'+esc(j.phone||'—')+'</p></div><div class="print-card"><h4>Jármű</h4><p><b>'+esc(j.car)+'</b><br>'+esc(j.plate||'—')+' · '+(j.year||'—')+' · '+(j.km?Number(j.km).toLocaleString('hu-HU')+' km':'—')+'</p></div></div><div class="print-card"><h4>Szolgáltatás és tételek</h4><table class="print-items"><thead><tr><th>Tétel</th><th>Érték</th></tr></thead><tbody><tr><td>'+esc(j.serviceName)+'</td><td>'+money(j.servicePrice)+'</td></tr>'+(j.extras||[]).map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+money(x.price)+'</td></tr>').join('')+'</tbody></table><div class="print-total"><div class="print-total-row"><span>Részösszeg</span><b>'+money(sub)+'</b></div><div class="print-total-row"><span>Kedvezmény</span><b>−'+money(j.discount)+'</b></div><div class="print-total-row final"><span>Fizetendő</span><b>'+money(j.total)+'</b></div><div class="print-total-row"><span>Fizetési mód</span><b>'+esc(j.paymentMethod||'—')+'</b></div></div></div><div class="print-grid" style="margin-top:7mm"><div class="print-card"><h4>Megjegyzés</h4><p>'+esc(j.note||'Nincs megjegyzés.').replace(/\\n/g,'<br>')+'</p></div><div class="print-card"><h4>Státusz</h4><p><b>'+((closed(j))?'LEZÁRVA':'NYITOTT')+'</b><br>Anyagköltség: '+money(j.cost)+'</p></div></div><div class="print-checks"><div class="check">'+(j.checklist?.before?'☑':'☐')+' BEFORE</div><div class="check">'+(j.checklist?.damage?'☑':'☐')+' Sérülés</div><div class="check">'+(j.checklist?.after?'☑':'☐')+' AFTER</div></div>'+(ph.length?'<div class="print-photos">'+ph.slice(0,6).map(p=>'<div class="print-photo"><img src="'+p.data+'"><small>'+esc(p.label||'Fotó')+'</small></div>').join('')+'</div>':'')+'<div class="print-footer"><span>D-Tail Studio · '+esc(j.id)+'</span><span>Generálva: '+new Intl.DateTimeFormat('hu-HU',{dateStyle:'medium',timeStyle:'short'}).format(new Date())+'</span></div></div>';window.print()}
function printReport(){const n=new Date(),a=state.jobs.filter(j=>closed(j)&&D(j.startAt).getFullYear()===n.getFullYear()&&D(j.startAt).getMonth()===n.getMonth()),rev=a.reduce((s,j)=>s+j.total,0),cost=a.reduce((s,j)=>s+j.cost,0);$('printSheet').innerHTML='<div class="print-page"><div class="print-header"><div class="print-brand"><div class="print-mark">D-Tail</div><div><div class="print-title">D-Tail Studio</div><div class="print-sub">Havi üzleti riport</div></div></div><div class="print-id"><b>'+new Intl.DateTimeFormat('hu-HU',{month:'long',year:'numeric'}).format(n)+'</b></div></div><div class="print-grid"><div class="print-card"><h4>Havi bevétel</h4><p style="font-size:18px"><b>'+money(rev)+'</b></p></div><div class="print-card"><h4>Becsült fedezet</h4><p style="font-size:18px"><b>'+money(rev-cost)+'</b></p></div></div><div class="print-card"><h4>Havi munkák</h4><table class="print-items"><thead><tr><th>Dátum</th><th>Ügyfél</th><th>Szolgáltatás</th><th>Bevétel</th><th>Anyag</th></tr></thead><tbody>'+a.map(j=>'<tr><td>'+fmtDate(j.startAt)+'</td><td>'+esc(j.customerName)+'</td><td>'+esc(j.serviceName)+'</td><td>'+money(j.total)+'</td><td>'+money(j.cost)+'</td></tr>').join('')+'</tbody></table></div></div>';window.print()}
function exportData(){const x={version:43,exportedAt:new Date().toISOString(),jobs:state.jobs,customers:state.customers,cars:state.cars,stock:state.stock,photos:state.photos,goal:state.goal,recipes:state.recipes,stockMovements:state.stockMovements},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:'application/json'}));a.download='dtail-studio-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importJson(file){file.text().then(t=>{const x=JSON.parse(t);state.jobs=migrateJobs(x.jobs);state.customers=x.customers||[];state.cars=x.cars||[];state.stock=normalizeStock(x.stock);state.photos=x.photos||{};state.goal=Number(x.goal)||1000000;state.recipes=x.recipes||defaultRecipes();state.stockMovements=Array.isArray(x.stockMovements)?x.stockMovements:[];save();renderAll();toast('Mentés betöltve')}).catch(()=>toast('Hibás JSON'))}
function renderAll(){greeting();renderDashboard();renderJobs();renderCustomers();renderCalendar();renderInventory();renderAnalytics();renderSettings()}
function toast(t){const e=$('toast');e.textContent=t;e.style.display='block';clearTimeout(window.__dt);window.__dt=setTimeout(()=>e.style.display='none',2200)}
function boot(){try{load();renderAll();setTimeout(()=>{$('boot')?.classList.add('hide');setTimeout(()=>$('boot')?.remove(),450)},400)}catch(e){console.error('D-Tail boot',e);$('boot')?.classList.add('hide')}}
document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('show'));
 document.querySelectorAll('[data-action="new-job"]').forEach(b=>b.onclick=()=>openNew());
 document.querySelectorAll('[data-action="new-customer"]').forEach(b=>b.onclick=()=>openCustomer());
 document.querySelectorAll('[data-action="add-stock"]').forEach(b=>b.onclick=addStock);
 $('menu').onclick=()=>document.body.classList.toggle('drawer');$('overlay').onclick=()=>document.body.classList.remove('drawer');
 $('globalSearch').onclick=()=>{showView('jobs');setTimeout(()=>$('jobSearch').focus(),20)};$('quickNew').onclick=()=>openNew();
 $('fDiscount').oninput=()=>{if(state.editJob)state.autoDiscount=false;renderCart()};$('fCustomer').oninput=applyLoyaltyDiscount;$('fDate').oninput=renderCart;$('fDuration').oninput=renderCart;$('saveJobBtn').onclick=saveJob;
 $('jobSearch').oninput=renderJobs;$('jobFilter').onchange=renderJobs;$('customerSearch').oninput=renderCustomers;
 $('calPrev').onclick=()=>{state.cal=new Date(state.cal.getFullYear(),state.cal.getMonth()-1,1);renderCalendar()};$('calNext').onclick=()=>{state.cal=new Date(state.cal.getFullYear(),state.cal.getMonth()+1,1);renderCalendar()};
 $('inventorySearch').oninput=renderInventory;$('inventoryStatus').onchange=renderInventory;$('inventoryCategory').onchange=renderInventory;$('stockRestock').onclick=addStock;$('recipeAddLine').onclick=addRecipeLine;$('recipeSave').onclick=saveRecipe;$('stockPackQty').oninput=previewNewStockCost;$('stockPackUnit').onchange=previewNewStockCost;$('stockPackPrice').oninput=previewNewStockCost;$('stockUnit').onchange=previewNewStockCost;$('saveInventory').onclick=saveInventory;$('inventoryEditor').onclick=e=>{const b=e.target.closest('[data-delete-stock]');if(b)deleteStock(b.dataset.deleteStock)};
 $('saveCustomerBtn').onclick=saveCustomer;$('saveStockBtn').onclick=saveStock;$('printReport').onclick=printReport;$('exportData').onclick=exportData;$('importFile').onchange=e=>e.target.files[0]&&importJson(e.target.files[0]);
 $('importLegacy').onclick=()=>{state.jobs=migrateJobs(read('dtail_jobs',[]));state.customers=read('dtail_customers',[]);const s=read('dtail_inventory_v2',[]);state.stock=normalizeStock(s.length?s:DEFAULT_STOCK);save();renderAll();toast('Régi adatok importálva')};
 $('clearLocal').onclick=()=>{if(confirm('A helyi D-Tail adatok törlődnek. Folytatod?')){localStorage.removeItem(KEY);location.reload()}};
 $('saveGoal').onclick=()=>{state.goal=Number($('goalInput').value)||0;save();renderAll();toast('Havi cél mentve')};
 $('cloudRefresh').onclick=()=>toast('A stabil alap most helyi módban fut.');
 boot();
},{once:true});
})();